version: "3"

services: 
  #Database
  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3308:3306'
    restart: always   
    

#Golang App   
  app:
    depends_on:
      - db
    build: .
    restart: on-failure:10